version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "/flutter_secure_storage"
    reviewers:
      - "westracer"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "pub"
  - package-ecosystem: "gradle"
    directory: "/flutter_secure_storage/android"
    schedule:
      interval: "daily"
    reviewers:
      - "westracer"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "maven"
