name: flutter_secure_storage_linux
description: Linux implementation of flutter_secure_storage
repository: https://github.com/mogol/flutter_secure_storage
version: 2.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    git:
      url: git@github.com:QuickBirdEng/flutter_secure_storage.git
      path: flutter_secure_storage_platform_interface
      ref: develop

flutter:
  plugin:
    implements: flutter_secure_storage
    platforms:
      linux:
        pluginClass: FlutterSecureStorageLinuxPlugin
