name: integration test
on: [pull_request]
jobs:
  drive_android:
      runs-on: macos-latest
      strategy:
        matrix:
          api-level: [31]
          target: [default]
      steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2.6.2
        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '11'
        - name: "Run Flutter Driver tests"
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: ${{ matrix.api-level }}
            target: ${{ matrix.target }}
            arch: x86_64
            profile: Nexus 6
            script: "cd example && flutter drive --target=test_driver/app.dart"
            working-directory: ./flutter_secure_storage
